//? College names list
List<String> collegeList = [
  "Veermata Jijabai Technological Institute (VJTI)",
  "Dwarkadas J. Sanghvi College of Engineering (DJSCE)",
  "Ramrao Adik Institute of Technology (RAIT)",
  "Fr. Conceicao Rodrigues College of Engineering (FRCRCE)",
  "K.J. Somaiya College of Engineering (KJSCE)",
  "Thakur College of Engineering and Technology (TCET)",
  "Anjuman-I-Islam's M.H. Saboo Siddik College of Engineering",
  "Mumbai Academy of Management Studies (MAMS)",
  "Sardar Patel Institute of Technology (SPIT)",
  "Vidyalankar Institute of Technology (VIT)",
  "Terna Engineering College (TEC)",
  "New Horizon College of Engineering (NHCE)",
  "DY Patil College of Engineering",
  "Dr. DY Patil Institute of Technology and Research (DYPITR)",
  "Universal College of Engineering (UCE)",
  "Pillai HOC College of Engineering and Technology",
  "A.P. Shah Institute of Technology (APSIT)",
  "Vivekanand Education Society's Institute of Technology (VESIT)",
  "Sardar Patel College of Engineering (SPCE)",
  "Don Bosco Institute of Technology (DBIT)",
  "P.K. Thakur College of Engineering (PKTC)",
];

//? Branch names list
List<String> branchList = [
  "Computer Science Engineering",
  "Electrical Engineering",
  "Mechanical Engineering",
  "Civil Engineering",
  "Electronics and Communication Engineering",
  "Information Technology",
  "Chemical Engineering",
  "Biotechnology",
  "Instrumentation Engineering",
  "Aeronautical Engineering",
  "Automobile Engineering",
  "Electrical and Electronics Engineering",
  "Environmental Engineering",
  "Industrial Engineering",
  "Materials Science and Engineering",
  "Petroleum Engineering",
  "Robotics Engineering",
  "Structural Engineering",
  "Telecommunication Engineering",
  "Biomedical Engineering",
  "Power Engineering",
  "Production Engineering",
  "Textile Engineering",
  "Naval Architecture and Marine Engineering",
  "Metallurgical Engineering",
  "Mining Engineering",
  "Agricultural Engineering",
  "Geo-informatics",
  "Nuclear Engineering",
];

//? Semesters list
List<String> semesterList = [
  '1',
  '2',
  '3',
  '4',
  '5',
  '6',
  '7',
  '8',
];
